import os
import os
from enum import IntEnum


# 定数定義
# フェーズ定義
class Phase(IntEnum):
    PHASE0 = 0
    PHASE1 = 1
    PHASE2 = 2
    PHASE3 = 3
    PHASE4 = 4
    PHASE5 = 5
    PHASE6 = 6
    PHASE7 = 7

# ログ関連定数
LOG_DIR = "./log"
LOG_PREFIX = "robust_log_"
LOG_FILE_DATETIME_FORMAT = "%Y-%m%d-%H%M%S"

# ターゲット座標
TARGET_LAT = 30.374217
TARGET_LNG = 130.959968

# タイムアウトと動作関連定数
TIMEOUT_PHASE_0 = 3 * 60
TIMEOUT_PHASE_1 = 30
TIMEOUT_PHASE_2 = 30
TIMEOUT_PHASE_3 = 5 * 60
TIMEOUT_PHASE_4 = 60
TIMEOUT_PHASE_5 = 45
# Phase4タイムアウト起因でPhase5へ入った場合は、
# 視覚未検出のまま長時間走行するリスクが高いため短縮する。
TIMEOUT_PHASE_5_AFTER_PHASE4_TIMEOUT = 20
DATA_SAMPLING_RATE = 0.06
PHASE6_RAM_SPEED = 25
PHASE6_RAM_DURATION_SEC = 2.5

# ミッション全体のフェーズ累積予算
# Phase3-5 は再入を考慮して、個別タイムアウトより大きい累積値を持たせる
MISSION_PHASE_TIME_BUDGETS = {
    Phase.PHASE0: TIMEOUT_PHASE_0,  # 降下待機
    Phase.PHASE1: TIMEOUT_PHASE_1,  # パラ分離
    Phase.PHASE2: TIMEOUT_PHASE_2,  # キャリブレーション
    Phase.PHASE3: 7 * 60,           # GPS航行
    Phase.PHASE4: 90,               # カメラ探索(複数回)
    Phase.PHASE5: 90,               # 接近(複数回)
}
MISSION_PHASE_BUDGET_TOTAL = sum(MISSION_PHASE_TIME_BUDGETS.values())
# 全体タイムアウトは「フェーズ累積予算合計 + 最終突入 + 遷移吸収マージン」で導出する。
# 現在値は 960 + 2.5 + 5.0 = 967.5 秒 (約 16 分 7.5 秒)。
MISSION_TIMEOUT_TRANSITION_GRACE_SEC = 5.0
MISSION_TIMEOUT_TOTAL = (
    MISSION_PHASE_BUDGET_TOTAL
    + PHASE6_RAM_DURATION_SEC
    + MISSION_TIMEOUT_TRANSITION_GRACE_SEC
)

MISSION_PHASE_TIMEOUT_TRANSITIONS = {
    Phase.PHASE0: Phase.PHASE1,
    Phase.PHASE1: Phase.PHASE2,
    Phase.PHASE2: Phase.PHASE3,
    Phase.PHASE3: Phase.PHASE4,
    Phase.PHASE4: Phase.PHASE5,
    Phase.PHASE5: Phase.PHASE6,
    Phase.PHASE6: Phase.PHASE7,
}

# センサーと動作の閾値
IMPACT_FALL_THRESHOLD = 30.0
DROP_ALTITUDE_DIFF_THRESHOLD = 20.0
PHASE0_DROP_TO_PHASE1_DELAY_SEC = 5.0

# コーン検出関連定数
CONE_PROBABILITY_THRESHOLD = 0.10
# Field runs show the cone is consistently boxed around prob~=0.23 in Phase4.
# Phase4 should accept that signal instead of holding forever on "low-confidence".
CONE_PROBABILITY_THRESHOLD_PHASE4 = 0.20
CONE_PROBABILITY_THRESHOLD_PHASE5 = 0.18
CONE_PHASE4_CONFIRM_FRAMES = 2
CONE_PHASE4_CENTER_TOLERANCE = 0.42
CONE_PHASE4_STRONG_PROBABILITY = 0.30
CONE_LOST_COUNT_LIMIT = 10
CONE_CENTER_POSITION = 0.5

# パラシュート展開関連定数
PARACHUTE_DIRECTION = -400.0
PARACHUTE_SEPARATION_SPEED = 100
PARACHUTE_MOTOR_PULSE = 0.05
# フェーズ1はサブキャリア内で初動トルクが大きくなりやすいため、
# 他フェーズより長いランプ時間と細かいステップで突入電流を抑える。
PHASE1_SOFTSTART_RAMP_TIME = 1.2
PHASE1_SOFTSTART_STEP = 0.01

# キャリブレーション関連定数
CALIBRATION_TURN_SPEED = 60
CALIBRATION_MAG_THRESHOLD = 2

# 障害物回避関連定数
OBSTACLE_AVOID_DIST = 30.0
OBSTACLE_CONFIRM_COUNT = 3
OBSTACLE_SPEED = 60
OBSTACLE_BACKUP_TIME = 1.0
OBSTACLE_TURN_TIME = 0.5
OBSTACLE_PAUSE_TIME = 0.2

# カメラ関連定数
CAMERA_ACTIVE_SLEEP = 0.02
CAMERA_IDLE_SLEEP = 0.5
CAMERA_REINIT_INTERVAL = 5.0
CAMERA_FAIL_LIMIT = 5
CAMERA_DEAD_TIMEOUT = 30.0
CAMERA_PHASE4_MAX_ATTEMPTS = 3
CAMERA_PHASE5_MAX_ATTEMPTS = 3
CAMERA_TEMPORAL_MIN_PROBABILITY = 0.12
CAMERA_TEMPORAL_STRONG_PROBABILITY = 0.42
CAMERA_TEMPORAL_DIR_JUMP_MAX = 0.18
CAMERA_TEMPORAL_CONFIRM_FRAMES = 2
CAMERA_TEMPORAL_HOLD_SEC = 0.35
CAMERA_TEMPORAL_DIR_FILTER_ALPHA = 0.45

# ロゴ保存パス
# ROI画像はホーム配下の固定パスを常に参照する
ROI_CAPTURE_DIR = os.path.expanduser("~/library/log")
ROI_PATH_1 = os.path.join(ROI_CAPTURE_DIR, "captured_roi_img.png")
# 後方互換のため残すが、実体は同一ファイルを指す
ROI_PATH_2 = ROI_PATH_1
ROI_GLOB_PATTERNS = (
    "captured_roi_img*.png",
    "captured_roi_img*.jpg",
    "captured_roi_img*.jpeg",
    "roi_cone*.png",
    "roi_cone*.jpg",
    "roi_cone*.jpeg",
    "false_*.png",
    "false_*.jpg",
    "false_*.jpeg",
    "fake_*.png",
    "fake_*.jpg",
    "fake_*.jpeg",
)

# モーター制御関連定数
SEARCH_ROTATION_SPEED = 45
PHASE4_SEARCH_SWEEP_INTERVAL = 2.0
PHASE4_TRACK_ROTATE_GAIN = 60
PHASE4_TRACK_ROTATE_CLAMP = 18
PHASE4_TRACK_MIN_ROTATE_SPEED = 5
PHASE4_ALIGN_STOP_DEADBAND = 0.04
PHASE4_ALIGN_ARC_DEADBAND = 0.18
PHASE4_ALIGN_FORWARD_SPEED = 80
PHASE4_ALIGN_PIVOT_SPEED = 100
PHASE4_ALIGN_ARC_BASE_SPEED = 80
PHASE4_ALIGN_ARC_TURN_GAIN = 30
APPROACH_TURN_GAIN = 52
PHASE5_BASE_SPEED = 80
PHASE5_TURN_CLAMP = 22
PHASE5_STEER_DEADBAND = 0.03
PHASE45_CONE_DIR_FILTER_ALPHA = 0.72
PHASE4_MOTOR_RAMP_TIME = 0.06
PHASE5_MOTOR_RAMP_TIME = 0.05
PHASE45_MOTOR_LOOP_INTERVAL = 0.02
BASE_SPEED = 100
PHASE3_NO_HEADING_SPEED = 100
PHASE3_NO_HEADING_TURN_BIAS = 20
PHASE3_NO_HEADING_TURN_INTERVAL = 2.5
PHASE3_FORWARD_SPEED = 100
PHASE3_TURN_OUTER_SPEED = 62.5
PHASE3_TURN_INNER_SPEED = 37.5
PHASE3_HEADING_DEADBAND_DEG = 5.0
PHASE3_GPS_FALLBACK_DEADBAND_DEG = 12.0
PHASE3_GPS_FALLBACK_TURN_SCALE = 0.45
PHASE3_MAG_STUCK_TIMEOUT_SEC = 1.5
PHASE3_MAG_STUCK_MIN_DELTA_DEG = 3.0
PHASE3_TURN_FAST_SPEED = 100
PHASE3_TURN_SLOW_SPEED = 75
PHASE3_TURN_FULL_ERROR_DEG = 45.0
PHASE3_PIVOT_THRESHOLD_DEG = 75.0
PHASE3_PIVOT_SPEED = 34
PHASE3_PIVOT_SLOW_MIN_SPEED = 20
PHASE3_BNO_GPS_OFFSET_ALPHA = 0.2
PHASE3_BNO_GPS_OFFSET_MAX_STEP_DEG = 45.0
PHASE3_FORWARD_RAMP_TIME = 0.2
PHASE3_TURN_RAMP_TIME = 0.1
MOTOR_LOOP_INTERVAL = 0.05
MOTOR_IDLE_SLEEP = 0.1
MOTOR_RAMP_TIME = 0.6
MOTOR_RAMP_STEP = 0.05
MOTOR_DIR_INVERT_1 = False
MOTOR_DIR_INVERT_2 = False
MANUAL_TURN_SPEED_RATIO = 3.0 / 5.0
# モーター個体差補正 (PWM指令値に乗算)
MOTOR_SPEED_SCALE_1 = 1.00
MOTOR_SPEED_SCALE_2 = 1.00
# モーター個体差補正 (PWM指令値に加算, scale適用後)
# 例: MTR1がまだ速いなら MOTOR_SPEED_OFFSET_1 = -2.0 のように下げる
MOTOR_SPEED_OFFSET_1 = 0.0
MOTOR_SPEED_OFFSET_2 = 0.0

# LED関連定数
LED_INTERVAL_PHASE0 = 5
LED_INTERVAL_PHASE2 = 3
LED_INTERVAL_PHASE3 = 10
LED_INTERVAL_PHASE3_NEAR = 2
LED_INTERVAL_PHASE5 = 2
LED_SIGNAL_SLEEP = 0.2
LED_SIGNAL_COUNT = 3
LED_TIMEOUT_ALERT_FLASH_COUNT = 24
LED_TIMEOUT_ALERT_FAST_SLEEP = 0.08

# モーター・センサーのGPIO関連定数
# Motor mapping (fixed): MTR1=LEFT, MTR2=RIGHT
PIN_EN1 = 12
PIN_PH1 = 13
PIN_EN2 = 19
PIN_PH2 = 17
PWM_FREQ = 1000
PIN_LED_RED = 6
PIN_LED_GREEN = 5
PIN_TRIG = 23
PIN_ECHO = 24
SONAR_MAX_DISTANCE = 4.0

# GPS関連定数
GPS_SERIAL_PORT = "/dev/serial0"
GPS_SERIAL_PORT_CANDIDATES = ["/dev/serial0", "/dev/ttyAMA0", "/dev/ttyS0"]
GPS_BAUDRATE = 9600
# Common GPS module UART rates (u-blox often ships at 9600/38400, some setups use 115200).
GPS_BAUDRATE_CANDIDATES = [9600, 38400, 115200, 57600, 19200, 4800]
GPS_SERIAL_TIMEOUT = 1
GPS_SERIAL_DISCOVERY_TIMEOUT = 0.2
GPS_HEADING_OFFSET = 5.43
GPS_TURN_GAIN = 0.3
GPS_TURN_CLAMP = 30.0
GPS_CLOSE_DISTANCE = 3.0
GPS_PHASE45_MAX_DISTANCE = 10.0 
GPS_BUFFER_CLEAR_THRESHOLD = 2048
GPS_BUFFER_CLEAR_INTERVAL = 5.0
GPS_MIN_FIX_QUAL = 1
GPS_MIN_SATELLITES = 4
GPS_MAX_HDOP = 5.0
GPS_MAX_SPEED_MPS = 10.0
GPS_STABLE_FIX_COUNT = 3
GPS_FIX_LOSS_TIMEOUT = 8.0
GPS_HEADING_MIN_DIST = 0.2
GPS_HEADING_BASELINE_MIN_DIST = 0.2
GPS_HEADING_WINDOW_SEC = 8.0
GPS_HEADING_HOLD_SEC = 2.5
HEADING_OFFSET_LEARN_MIN_SPEED_MPS = 0.8
HEADING_OFFSET_LEARN_BOOTSTRAP_SAMPLES = 5
HEADING_OFFSET_LEARN_MAX_RESIDUAL_DEG = 20.0
GPS_COORD_LAT_OFFSET_DEG = 0.0
GPS_COORD_LNG_OFFSET_DEG = 0.0
GPS_PROBE_SECONDS = 2.0
GPS_STARTUP_SYNC_SECONDS = 8.0
GPS_STARTUP_READ_SIZE = 256
GPS_RECONNECT_SLEEP = 1.0
GPS_NO_DATA_REOPEN_TIMEOUT = 12.0
GPS_NON_GGA_REOPEN_TIMEOUT = 20.0
GPS_ACTIVE_DETECT = 1
GPS_INACTIVE_DETECT = 0
GPS_DIAGNOSTIC_LOG_INTERVAL = 5.0

# BNO055関連定数
BNO_SETUP_RETRY_COUNT = 3
BNO_SETUP_RETRY_INTERVAL = 0.5
BNO_INIT_READY_TIMEOUT = 2.5
BNO_INIT_SAMPLE_INTERVAL = 0.1
BNO_FAIL_LIMIT = 10
BNO_REINIT_COOLDOWN = 3.0
BNO_ACC_MAX = 200.0
BNO_GYRO_MAX = 2000.0
BNO_MAG_MAX = 2000.0
BNO_ANGLE_JUMP_MAX = 60.0
BNO_CALIB_MAG_MIN = 2
BNO_STALE_TIMEOUT = 2.0
BNO_FREEZE_EPS = 0.001
BNO_FUSION_OK_STATES = (5, 6)
PHASE0_SENSOR_STALE_TIMEOUT = 1.5

# BMP180関連定数
BMP_SEA_LEVEL_PRESSURE_PA = 101325.0
BMP_PRESSURE_MIN_VALID = 30000.0
BMP_PRESSURE_MAX_VALID = 120000.0
BMP_ALTITUDE_MIN_VALID = -500.0
BMP_ALTITUDE_MAX_VALID = 10000.0

# PHASE2関連定数
PHASE2_STRAIGHT_TIME = 6.0
# Keep the initial straight run intact, but shorten figure-8 calibration so
# Phase2 exits earlier when magnetometer calibration does not improve.
PHASE2_FIG8_TIME = 15.0
PHASE2_TURN_INTERVAL = 3.0
PHASE2_SPEED = 100
PHASE2_TURN_BIAS = 40
PHASE2_RAMP_TIME = 0.2
PHASE2_STAGE_STRAIGHT = "straight"
PHASE2_STAGE_FIG8 = "fig8"

# その他定数
EARTH_RADIUS_METERS = 6378137.0
MILLISECOND_SCALE = 1000
DEGREE_FULL_CIRCLE = 360.0
DEGREE_HALF_CIRCLE = 180.0
HEADING_SOURCE_INVALID = "INVALID"
HEADING_SOURCE_GPS = "GPS"
HEADING_SOURCE_BNO = "BNO"
HEADING_SOURCE_JOINER = "+"
HEADING_WEIGHT_GPS = 0.65
HEADING_WEIGHT_BNO_BASE = 0.35
HEADING_WEIGHT_BNO_STEP = 0.1
HEADING_WEIGHT_BNO_MIN = 0.25
HEADING_WEIGHT_BNO_MAX = 0.7
HEADING_MAG_CALIB_MAX = 3

# ログとループ関連定数
PHASE_LOG_INTERVAL = 10
GPS_LOST_LOG_INTERVAL = 20
MAIN_LOOP_INTERVAL = 0.1
SHORT_SLEEP = MAIN_LOOP_INTERVAL

# モーター制御のランプアップ・ダウン関連定数
RAMP_HALF_DIVISOR = 2.0
PWM_PERCENT_MIN = 0.0
PWM_PERCENT_MAX = 100.0
PWM_DUTY_MIN = 0.0
PWM_DUTY_MAX = 1.0
TURN_GAIN_SCALE_MIN = 0.5
TURN_GAIN_SCALE_MAX = 1.0

# デフォルト値
DEFAULT_VECTOR3 = (0.0, 0.0, 0.0)
DEFAULT_BNO_CALIB = {"valid": False, "value": (0, 0, 0, 0)}
DEFAULT_OBSTACLE_DIST_CM = 999.0
DEFAULT_FLOAT_VALUE = 0.0
DEFAULT_PHASE = int(Phase.PHASE0)

# NMEA関連定数
NMEA_GGA_PREFIXES = ("$GPGGA", "$GNGGA")
NMEA_SENTENCE_GGA = "GGA"

# デバイスキー
DEVICE_BNO = "bno"
DEVICE_BMP = "bmp"
DEVICE_DETECTOR = "detector"
DEVICE_LED_RED = "led_red"
DEVICE_LED_GREEN = "led_green"
DEVICE_MOTOR_1_PWM = "motor_1_pwm"
DEVICE_MOTOR_1_DIR = "motor_1_dir"
DEVICE_MOTOR_2_PWM = "motor_2_pwm"
DEVICE_MOTOR_2_DIR = "motor_2_dir"
DEVICE_SONAR = "sonar"
DEVICE_KEYS = (
    DEVICE_BNO,
    DEVICE_BMP,
    DEVICE_DETECTOR,
    DEVICE_LED_RED,
    DEVICE_LED_GREEN,
    DEVICE_MOTOR_1_PWM,
    DEVICE_MOTOR_1_DIR,
    DEVICE_MOTOR_2_PWM,
    DEVICE_MOTOR_2_DIR,
    DEVICE_SONAR,
)

# フェーズごとの動作制御関連定数
PHASES_STOP_MOTORS = (Phase.PHASE0, Phase.PHASE7)
PHASES_SKIP_OBSTACLE = (Phase.PHASE0, Phase.PHASE1, Phase.PHASE5, Phase.PHASE6, Phase.PHASE7)
PHASES_CAMERA_ACTIVE = (Phase.PHASE4, Phase.PHASE5)

# ログのヘッダー
LOG_HEADER = [
    "ElapsedSec",
    "Phase",
    "AccX",
    "AccY",
    "AccZ",
    "GyroX",
    "GyroY",
    "GyroZ",
    "MagX",
    "MagY",
    "MagZ",
    "LAT",
    "LNG",
    "GpsSpeedMps",
    "GPSFixQual",
    "GPSSats",
    "GPSHdop",
    "ALT",
    "Pres",
    "Distance",
    "Azimuth",
    "TargetLat",
    "TargetLng",
    "Angle",
    "Direction",
    "Fall",
    "ConeDir",
    "ConeProb",
    "ConeMethod",
    "ObstacleDist",
    "AngleValid",
    "BNOStaleSec",
    "BNOAccValid",
    "BNOAccStaleSec",
    "BMPValid",
    "BMPStaleSec",
    "MotorCmdType",
    "MotorCmdUpdatedElapsedSec",
    "Motor1CmdSpeed",
    "Motor1CmdForward",
    "Motor2CmdSpeed",
    "Motor2CmdForward",
    "Phase7ArrivalReason",
    "MissionEndReason",
    "MissionTotalTimeout",
    "MissionElapsedSec",
]
